apiVersion: v1
kind: Service
metadata:
  name: {{ include "website.fullname" . }}
  labels:
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    {{- include "website.selectorLabels" . | nindent 4 }}
