name: Basic website checks
on:
  pull_request:
    branches:
      - main

env:
  site_name: "deploy-preview-${{ GITHUB_SHA }}-bia-beta-website"

jobs:
  wait-for-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Waiting for 200 from the Netlify Preview
        uses: jakepartusch/wait-for-netlify-action@v1.4
        with:
          site_name: $site_name
          max_timeout: 60

  link-check:
    needs: wait-for-deploy
    runs-on: ghcr.io/linkchecker/linkchecker:latest
    steps:
      - run: linkchecker  https://deploy-preview-4--bia-beta-website.netlify.app/bioimage-archive/ -o failures
