name: Basic website checks
on:
  pull_request:
    branches:
      - main

env:
  site_name: bia-beta-website # remainder added by netlify

jobs:
  wait-for-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Waiting for 200 from the Netlify Preview
        uses: jakepartusch/wait-for-netlify-action@v1.4
        with:
          site_name: ${{ env.site_name }}
          max_timeout: 60

  link-check:
    needs: wait-for-deploy
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/linkchecker/linkchecker:latest
    steps:
      - run: |
          # no-warnings because linkchecker runs as root in container -> warning emitted -> nonzero return code -> job fails
          linkchecker https://deploy-preview-${{ github.event.number }}--${{ env.site_name }}.netlify.app/bioimage-archive/ -o failures \
            --no-warnings \
            --ignore-url '.*\/vis\/?.*' \
            --ignore-url '.*\/dataset\/?.*' \
            --ignore-url '.*\/sodataset\/?.*' \
            --ignore-url '.*\/aidataset\/?.*'
